language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer selfupdate
    - composer install --dev --prefer-dist --no-interaction

script: phpunit --coverage-clover /tmp/coverage.xml
